#version: "3.9"
services:
    postgres:
      image: postgres:12-alpine
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=wallet_bank
    api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - DB_SOURCE=postgresql://root:secret@postgres:5432/wallet_bank?sslmode=disable
        - REDIS_ADDRESS=redis:6379
      depends_on:
        - postgres
        - redis
      entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
      command: ["./main"]

    redis:
      image: redis:latest
      container_name: redis
      restart: always
      volumes:
        - redis_data:/data
      command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local