// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Vallet struct {
	ValletID  int64     `json:"vallet_id"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}
