// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Wallet struct {
	WalletID  int64     `json:"wallet_id"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}
