// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Wallet struct {
	WalletUuid uuid.UUID `json:"wallet_uuid"`
	Balance    int64     `json:"balance"`
	CreatedAt  time.Time `json:"created_at"`
}
