// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateVallet(ctx context.Context, balance int64) (Vallet, error)
	GetVallet(ctx context.Context, valletID int64) (Vallet, error)
	UpdateValletBalance(ctx context.Context, arg UpdateValletBalanceParams) (Vallet, error)
}

var _ Querier = (*Queries)(nil)
